In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

ModuleNotFoundError: No module named 'pandas'

In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-2.2.5-cp310-cp310-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp310-cp310-win_amd64.whl (11.6 MB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
    --------------------------------------- 0.3/11.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.6 MB 3.6 MB/s eta 0:00:03
   ------ --------------------------------- 1.8/11.6 MB 3.5 MB/s eta 0:00:03
   --------- ------------------------------ 2.6/11.6 MB 3.6 MB/s eta 0:00:03
   ---------- ----------------------------- 3.1/11.6 MB 3.6 MB/s eta 0:00:03
   ------------ --------------------------- 3.7/11.6 MB 3.0 MB/s eta 0:00:03
   ------------- -------------------------- 3.9/11.6 MB 2.9 MB/s eta 0:00:03
   --------------- ------------------------ 4.5/11.6 MB 2.9 MB/s eta 0:00:03
   ----------------- ---------------------- 5.0/11.6 MB 2.8 MB/s eta 0:00:03
   ------------------ --------------------- 5.2/11.6 MB 2.6 MB/s eta 0:00:03
   ------------------ --------------------- 5.5/11.6 MB 2.5 MB/s eta 0:00:03
   -------------------- ------------------- 6.0/11.6 MB 2.4 MB/s eta 0:00:03
   ---------------------- ----------------- 6.6/11.6 MB 2.4 MB/s eta 0:00:03
   ----------------------- ---------------- 6.8/11.6 MB 2.4 MB/s eta 0:00:03
   ------------------------ --------------- 7.1/11.6 MB 2.3 MB/s eta 0:00:02
   -------------------------- ------------- 7.6/11.6 MB 2.3 MB/s eta 0:00:02
   ---------------------------- ----------- 8.1/11.6 MB 2.3 MB/s eta 0:00:02
   ------------------------------ --------- 8.9/11.6 MB 2.3 MB/s eta 0:00:02
   -------------------------------- ------- 9.4/11.6 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 10.0/11.6 MB 2.4 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.6 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 11.3/11.6 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.6 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 2.3 MB/s eta 0:00:00
Downloading numpy-2.2.5-cp310-cp310-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 1.7 MB/s eta 0:00:08
   --- ------------------------------------ 1.0/12.9 MB 2.2 MB/s eta 0:00:06
   ---- ----------------------------------- 1.6/12.9 MB 2.3 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.9 MB 2.3 MB/s eta 0:00:05
   -------- ------------------------------- 2.9/12.9 MB 2.5 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.9 MB 2.6 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.9 MB 2.4 MB/s eta 0:00:04
   ------------ --------------------------- 4.2/12.9 MB 2.3 MB/s eta 0:00:04
   -------------- ------------------------- 4.7/12.9 MB 2.3 MB/s eta 0:00:04
   ---------------- ----------------------- 5.2/12.9 MB 2.4 MB/s eta 0:00:04
   ------------------ --------------------- 6.0/12.9 MB 2.5 MB/s eta 0:00:03
   -------------------- ------------------- 6.6/12.9 MB 2.5 MB/s eta 0:00:03
   ---------------------- ----------------- 7.3/12.9 MB 2.6 MB/s eta 0:00:03
   ------------------------- -------------- 8.1/12.9 MB 2.6 MB/s eta 0:00:02
   -------------------------- ------------- 8.7/12.9 MB 2.7 MB/s eta 0:00:02
   ----------------------------- ---------- 9.4/12.9 MB 2.7 MB/s eta 0:00:02
   ------------------------------ --------- 10.0/12.9 MB 2.7 MB/s eta 0:00:02
   -------------------------------- ------- 10.5/12.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.9 MB 2.7 MB/s eta 0:00:01
   ------------------------------------ --- 11.8/12.9 MB 2.7 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  12.8/12.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 2.7 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.5 pandas-2.2.3 pytz-2025.2 tzdata-2025.2

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

ModuleNotFoundError: No module named 'matplotlib'

In [4]:
!pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.1-cp310-cp310-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.57.0-cp310-cp310-win_amd64.whl.metadata (104 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.8-cp310-cp310-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-11.2.1-cp310-cp310-win_amd64.whl.metadata (9.1 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Downloading pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.1-cp310-cp310-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.1 MB 2.1 MB/s eta 0:00:04
   ----- ---------------------------------- 1.0/8.1 MB 2.0 MB/s eta 0:00:04
   ------- -------------------------------- 1.6/8.1 MB 2.0 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.1 MB 2.2 MB/s eta 0:00:03
   ------------- -------------------------- 2.6/8.1 MB 2.3 MB/s eta 0:00:03
   ---------------- ----------------------- 3.4/8.1 MB 2.5 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.1 MB 2.5 MB/s eta 0:00:02
   ----------------------- ---------------- 4.7/8.1 MB 2.7 MB/s eta 0:00:02
   -------------------------- ------------- 5.2/8.1 MB 2.7 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.1 MB 2.6 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.1 MB 2.5 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.1 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.1 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 2.6 MB/s eta 0:00:00
Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl (221 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.57.0-cp310-cp310-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 4.2 MB/s eta 0:00:01
   ---------------------------- ----------- 1.6/2.2 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 3.4 MB/s eta 0:00:00
Downloading kiwisolver-1.4.8-cp310-cp310-win_amd64.whl (71 kB)
Downloading pillow-11.2.1-cp310-cp310-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ----------- ---------------------------- 0.8/2.7 MB 4.2 MB/s eta 0:00:01
   ----------------------- ---------------- 1.6/2.7 MB 3.8 MB/s eta 0:00:01
   ----------------------------------- ---- 2.4/2.7 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 3.7 MB/s eta 0:00:00
Downloading pyparsing-3.2.3-py3-none-any.whl (111 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.57.0 kiwisolver-1.4.8 matplotlib-3.10.1 pillow-11.2.1 pyparsing-3.2.3

In [5]:
%pip install pandas numpy matplotlib seaborn

Requirement already satisfied: pandas in c:\users\dell\.conda\envs\grocery1\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\dell\.conda\envs\grocery1\lib\site-packages (2.2.5)
Requirement already satisfied: matplotlib in c:\users\dell\.conda\envs\grocery1\lib\site-packages (3.10.1)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [7]:
# Load the dataset
df = pd.read_csv("grocery dataset.csv")

# Display the first few rows
df.head()

  user_id           item              dietary_tags purchase_date  season
0    U006   Coconut Milk        vegan, gluten-free    2024-03-14  Spring
1    U025  Peanut Butter  vegetarian, high-protein    2024-03-27  Spring
2    U034         Apples         vegan, vegetarian    2024-03-16  Spring
3    U037  Peanut Butter  vegetarian, high-protein    2024-04-12  Spring
4    U031           Kale         vegan, vegetarian    2024-01-19  Winter

In [8]:
# Check for missing values and data types
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   user_id        500 non-null    object
 1   item           500 non-null    object
 2   dietary_tags   481 non-null    object
 3   purchase_date  500 non-null    object
 4   season         500 non-null    object
dtypes: object(5)
memory usage: 19.7+ KB

user_id           0
item              0
dietary_tags     19
purchase_date     0
season            0
dtype: int64

In [9]:
# Convert purchase_date to datetime
df['purchase_date'] = pd.to_datetime(df['purchase_date'])

# Extract additional time features
df['month'] = df['purchase_date'].dt.month
df['day_of_week'] = df['purchase_date'].dt.dayofweek
df['day'] = df['purchase_date'].dt.day
df['year'] = df['purchase_date'].dt.year

df.head()

,user_id,item,dietary_tags,purchase_date,season,month,day_of_week,day,year
0,U006,Coconut Milk,"vegan, gluten-free",2024-03-14,Spring,3,3,14,2024
1,U025,Peanut Butter,"vegetarian, high-protein",2024-03-27,Spring,3,2,27,2024
2,U034,Apples,"vegan, vegetarian",2024-03-16,Spring,3,5,16,2024
3,U037,Peanut Butter,"vegetarian, high-protein",2024-04-12,Spring,4,4,12,2024
4,U031,Kale,"vegan, vegetarian",2024-01-19,Winter,1,4,19,2024

In [10]:
# Count number of purchases per user
user_purchase_freq = df['user_id'].value_counts().reset_index()
user_purchase_freq.columns = ['user_id', 'purchase_count']

# Merge back to the main dataframe
df = df.merge(user_purchase_freq, on='user_id', how='left')

df[['user_id', 'purchase_count']].drop_duplicates().head()

  user_id  purchase_count
0    U006              12
1    U025              15
2    U034              12
3    U037              10
4    U031              10

In [11]:
# Check and drop duplicates
print(f"Duplicates before: {df.duplicated().sum()}")
df.drop_duplicates(inplace=True)
print(f"Duplicates after: {df.duplicated().sum()}")

Duplicates before: 0
Duplicates after: 0

In [12]:
# Check unique values in season and dietary_tags
print("Seasons:", df['season'].unique())
print("\nSample dietary tags:")
print(df['dietary_tags'].sample(10).values)

Seasons: ['Spring' 'Winter']

Sample dietary tags:
['vegetarian' 'vegan, gluten-free' 'vegan, vegetarian' 'high-protein'
 'vegan, vegetarian' nan 'vegan, vegetarian' 'vegan, vegetarian'
 'vegan, vegetarian' 'vegetarian']

In [13]:
# Create a matrix where rows = users and columns = items
user_item_matrix = df.pivot_table(index='user_id', columns='item', 
                                  values='purchase_date', 
                                  aggfunc='count').fillna(0)

user_item_matrix.head()

item,Almond Milk,Apples,Avocados,Bananas,Beef,Broccoli,Brown Rice,Carrots,Cheese,Chicken Breast,...,Rice Cakes,Salmon,Soy Milk,Spinach,Sweet Potatoes,Tofu,Turkey,Whole Milk,Yogurt,Zucchini
user_id,,,,,,,,,,,,,,,,,,,,,
U001,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
U002,0.0,0.0,3.0,1.0,0.0,0.0,2.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,2.0
U003,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
U004,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0
U005,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0

In [14]:
%pip install sklearn

Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.

  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [15]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.6.1-cp310-cp310-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\dell\.conda\envs\grocery1\lib\site-packages (from scikit-learn) (2.2.5)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.15.2-cp310-cp310-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.6.1-cp310-cp310-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 3.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/11.1 MB 3.1 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/11.1 MB 2.7 MB/s eta 0:00:04
   ------- -------------------------------- 2.1/11.1 MB 2.6 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.1 MB 2.5 MB/s eta 0:00:04
   ----------- ---------------------------- 3.1/11.1 MB 2.5 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.1 MB 2.6 MB/s eta 0:00:03
   --------------- ------------------------ 4.2/11.1 MB 2.6 MB/s eta 0:00:03
   ----------------- ---------------------- 5.0/11.1 MB 2.7 MB/s eta 0:00:03
   ------------------- -------------------- 5.5/11.1 MB 2.7 MB/s eta 0:00:03
   --------------------- ------------------ 6.0/11.1 MB 2.7 MB/s eta 0:00:02
   ----------------------- ---------------- 6.6/11.1 MB 2.6 MB/s eta 0:00:02
   -------------------------- ------------- 7.3/11.1 MB 2.7 MB/s eta 0:00:02
   ---------------------------- ----------- 7.9/11.1 MB 2.7 MB/s eta 0:00:02
   ------------------------------ --------- 8.4/11.1 MB 2.7 MB/s eta 0:00:02
   -------------------------------- ------- 9.2/11.1 MB 2.7 MB/s eta 0:00:01
   ---------------------------------- ----- 9.7/11.1 MB 2.7 MB/s eta 0:00:01
   ------------------------------------- -- 10.5/11.1 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 2.7 MB/s eta 0:00:00
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.15.2-cp310-cp310-win_amd64.whl (41.2 MB)
   ---------------------------------------- 0.0/41.2 MB ? eta -:--:--
    --------------------------------------- 0.5/41.2 MB 3.4 MB/s eta 0:00:13
   - -------------------------------------- 1.3/41.2 MB 3.7 MB/s eta 0:00:11
   - -------------------------------------- 1.8/41.2 MB 3.5 MB/s eta 0:00:12
   -- ------------------------------------- 2.6/41.2 MB 3.2 MB/s eta 0:00:13
   --- ------------------------------------ 3.1/41.2 MB 3.1 MB/s eta 0:00:13
   --- ------------------------------------ 3.7/41.2 MB 2.9 MB/s eta 0:00:13
   ---- ----------------------------------- 4.2/41.2 MB 2.9 MB/s eta 0:00:13
   ---- ----------------------------------- 5.0/41.2 MB 3.0 MB/s eta 0:00:13
   ----- ---------------------------------- 5.5/41.2 MB 3.0 MB/s eta 0:00:12
   ------ --------------------------------- 6.3/41.2 MB 3.0 MB/s eta 0:00:12
   ------ --------------------------------- 7.1/41.2 MB 3.1 MB/s eta 0:00:12
   ------- -------------------------------- 7.9/41.2 MB 3.1 MB/s eta 0:00:11
   -------- ------------------------------- 8.4/41.2 MB 3.1 MB/s eta 0:00:11
   -------- ------------------------------- 9.2/41.2 MB 3.1 MB/s eta 0:00:11
   --------- ------------------------------ 9.7/41.2 MB 3.1 MB/s eta 0:00:11
   ---------- ----------------------------- 10.5/41.2 MB 3.1 MB/s eta 0:00:10
   ---------- ----------------------------- 11.3/41.2 MB 3.1 MB/s eta 0:00:10
   ----------- ---------------------------- 11.8/41.2 MB 3.1 MB/s eta 0:00:10
   ------------ --------------------------- 12.6/41.2 MB 3.1 MB/s eta 0:00:10
   ------------ --------------------------- 12.8/41.2 MB 3.1 MB/s eta 0:00:10
   ------------- -------------------------- 13.6/41.2 MB 3.0 MB/s eta 0:00:10
   ------------- -------------------------- 14.2/41.2 MB 3.0 MB/s eta 0:00:09
   -------------- ------------------------- 14.9/41.2 MB 3.1 MB/s eta 0:00:09
   --------------- ------------------------ 15.7/41.2 MB 3.1 MB/s eta 0:00:09
   --------------- ------------------------ 16.3/41.2 MB 3.1 MB/s eta 0:00:09
   ---------------- ----------------------- 17.3/41.2 MB 3.1 MB/s eta 0:00:08
   ----------------- ---------------------- 18.1/41.2 MB 3.2 MB/s eta 0:00:08
   ------------------ --------------------- 18.6/41.2 MB 3.1 MB/s eta 0:00:08
   ------------------ --------------------- 19.4/41.2 MB 3.2 MB/s eta 0:00:07
   ------------------- -------------------- 20.4/41.2 MB 3.2 MB/s eta 0:00:07
   -------------------- ------------------- 21.2/41.2 MB 3.2 MB/s eta 0:00:07
   --------------------- ------------------ 21.8/41.2 MB 3.2 MB/s eta 0:00:07
   --------------------- ------------------ 22.3/41.2 MB 3.2 MB/s eta 0:00:06
   ---------------------- ----------------- 22.8/41.2 MB 3.2 MB/s eta 0:00:06
   ---------------------- ----------------- 23.6/41.2 MB 3.2 MB/s eta 0:00:06
   ----------------------- ---------------- 24.1/41.2 MB 3.2 MB/s eta 0:00:06
   ------------------------ --------------- 24.9/41.2 MB 3.2 MB/s eta 0:00:06
   ------------------------ --------------- 25.7/41.2 MB 3.2 MB/s eta 0:00:05
   ------------------------- -------------- 26.2/41.2 MB 3.2 MB/s eta 0:00:05
   -------------------------- ------------- 27.0/41.2 MB 3.2 MB/s eta 0:00:05
   -------------------------- ------------- 27.8/41.2 MB 3.2 MB/s eta 0:00:05
   --------------------------- ------------ 28.6/41.2 MB 3.2 MB/s eta 0:00:04
   ---------------------------- ----------- 29.6/41.2 MB 3.2 MB/s eta 0:00:04
   ----------------------------- ---------- 30.4/41.2 MB 3.2 MB/s eta 0:00:04
   ------------------------------ --------- 30.9/41.2 MB 3.2 MB/s eta 0:00:04
   ------------------------------ --------- 31.5/41.2 MB 3.2 MB/s eta 0:00:04
   ------------------------------- -------- 32.0/41.2 MB 3.2 MB/s eta 0:00:03
   ------------------------------- -------- 32.5/41.2 MB 3.2 MB/s eta 0:00:03
   -------------------------------- ------- 33.0/41.2 MB 3.2 MB/s eta 0:00:03
   -------------------------------- ------- 33.8/41.2 MB 3.2 MB/s eta 0:00:03
   --------------------------------- ------ 34.3/41.2 MB 3.2 MB/s eta 0:00:03
   --------------------------------- ------ 34.9/41.2 MB 3.2 MB/s eta 0:00:03
   ---------------------------------- ----- 35.7/41.2 MB 3.2 MB/s eta 0:00:02
   ----------------------------------- ---- 36.2/41.2 MB 3.2 MB/s eta 0:00:02
   ----------------------------------- ---- 36.7/41.2 MB 3.2 MB/s eta 0:00:02
   ------------------------------------ --- 37.2/41.2 MB 3.1 MB/s eta 0:00:02
   ------------------------------------ --- 38.0/41.2 MB 3.1 MB/s eta 0:00:02
   ------------------------------------- -- 38.8/41.2 MB 3.1 MB/s eta 0:00:01
   -------------------------------------- - 39.3/41.2 MB 3.1 MB/s eta 0:00:01
   -------------------------------------- - 40.1/41.2 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------  40.9/41.2 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------  41.2/41.2 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 41.2/41.2 MB 3.1 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.6.1 scipy-1.15.2 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

# Transpose the matrix to get item-item similarity
item_similarity = cosine_similarity(user_item_matrix.T)

# Create a DataFrame for easier interpretation
item_similarity_df = pd.DataFrame(item_similarity, 
                                  index=user_item_matrix.columns, 
                                  columns=user_item_matrix.columns)

item_similarity_df.head()

item,Almond Milk,Apples,Avocados,Bananas,Beef,Broccoli,Brown Rice,Carrots,Cheese,Chicken Breast,...,Rice Cakes,Salmon,Soy Milk,Spinach,Sweet Potatoes,Tofu,Turkey,Whole Milk,Yogurt,Zucchini
item,,,,,,,,,,,,,,,,,,,,,
Almond Milk,1.000000,0.354787,0.356593,0.175412,0.261488,0.231326,0.173494,0.000000,0.358057,0.339683,...,0.277350,0.080064,0.181568,0.214834,0.452911,0.318142,0.115663,0.428086,0.213504,0.286446
Apples,0.354787,1.000000,0.243658,0.168550,0.452267,0.222277,0.133366,0.227273,0.330289,0.348155,...,0.213201,0.123091,0.372194,0.330289,0.391675,0.342381,0.088911,0.255945,0.205152,0.165145
Avocados,0.356593,0.243658,1.000000,0.180702,0.269374,0.178727,0.536180,0.091372,0.184428,0.262445,...,0.250000,0.453632,0.155870,0.516398,0.116642,0.163868,0.119151,0.146999,0.302422,0.442627
Bananas,0.175412,0.168550,0.180702,1.000000,0.335410,0.032969,0.296721,0.235970,0.081650,0.484123,...,0.316228,0.136931,0.276026,0.122474,0.355023,0.326464,0.131876,0.135582,0.243432,0.244949
Beef,0.261488,0.452267,0.269374,0.335410,1.000000,0.245737,0.344031,0.201008,0.304290,0.384900,...,0.412479,0.204124,0.360041,0.304290,0.192450,0.216295,0.245737,0.121268,0.045361,0.121716

In [17]:
def get_similar_items(item_name, top_n=5):
    if item_name not in item_similarity_df.columns:
        return f"'{item_name}' not found in dataset."
    similar_items = item_similarity_df[item_name].sort_values(ascending=False)
    return similar_items[1:top_n+1]

In [18]:
def recommend_items_for_user(user_id, top_n=5):
    if user_id not in user_item_matrix.index:
        return f"User '{user_id}' not found."
    
    user_data = user_item_matrix.loc[user_id]
    purchased_items = user_data[user_data > 0].index.tolist()

    recommendations = pd.Series(dtype="float64")

    for item in purchased_items:
        similar_items = item_similarity_df[item]
        recommendations = recommendations.add(similar_items, fill_value=0)

    # Remove already purchased items
    recommendations = recommendations.drop(labels=purchased_items, errors='ignore')
    return recommendations.sort_values(ascending=False).head(top_n)

In [19]:
from sklearn.preprocessing import MultiLabelBinarizer

# Convert dietary tags into list format
df['tags_list'] = df['dietary_tags'].apply(lambda x: x.split(", ") if pd.notnull(x) and x != "" else [])

# Binarize the tags
mlb = MultiLabelBinarizer()
tags_encoded = mlb.fit_transform(df['tags_list'])

# Create DataFrame of encoded tags
tags_df = pd.DataFrame(tags_encoded, columns=mlb.classes_)
df_tags = pd.concat([df[['item']], tags_df], axis=1).drop_duplicates().reset_index(drop=True)

df_tags.head()

            item  gluten-free  high-protein  vegan  vegetarian
0   Coconut Milk            1             0      1           0
1  Peanut Butter            0             1      0           1
2         Apples            0             0      1           1
3           Kale            0             0      1           1
4         Yogurt            0             0      0           1

In [20]:
# Set the item as index
tag_matrix = df_tags.set_index('item')

# Compute cosine similarity between items based on dietary tags
tag_similarity = cosine_similarity(tag_matrix)

# Create similarity DataFrame
tag_similarity_df = pd.DataFrame(tag_similarity, 
                                 index=tag_matrix.index, 
                                 columns=tag_matrix.index)

tag_similarity_df.head()

item,Coconut Milk,Peanut Butter,Apples,Kale,Yogurt,Oats,Whole Milk,Eggs,Quinoa,Chicken Breast,...,Zucchini,Turkey,Greek Yogurt,Rice Cakes,Beef,Spinach,Salmon,Cheese,Carrots,Lentils
item,,,,,,,,,,,,,,,,,,,,,
Coconut Milk,1.0,0.000000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,0.816497,0.000000,...,0.500000,0.000000,0.000000,0.500000,0.000000,0.500000,0.000000,0.000000,0.500000,0.408248
Peanut Butter,0.0,1.000000,0.500000,0.500000,0.707107,0.707107,0.707107,1.000000,0.408248,0.707107,...,0.500000,0.707107,1.000000,0.500000,0.707107,0.500000,0.707107,0.707107,0.500000,0.816497
Apples,0.5,0.500000,1.000000,1.000000,0.707107,0.707107,0.707107,0.500000,0.408248,0.000000,...,1.000000,0.000000,0.500000,0.500000,0.000000,1.000000,0.000000,0.707107,1.000000,0.816497
Kale,0.5,0.500000,1.000000,1.000000,0.707107,0.707107,0.707107,0.500000,0.408248,0.000000,...,1.000000,0.000000,0.500000,0.500000,0.000000,1.000000,0.000000,0.707107,1.000000,0.816497
Yogurt,0.0,0.707107,0.707107,0.707107,1.000000,1.000000,1.000000,0.707107,0.000000,0.000000,...,0.707107,0.000000,0.707107,0.707107,0.000000,0.707107,0.000000,1.000000,0.707107,0.577350

In [21]:
def recommend_items_by_tags(item_name, top_n=5):
    if item_name not in tag_similarity_df.columns:
        return f"'{item_name}' not found in item list."
    similar_items = tag_similarity_df[item_name].sort_values(ascending=False)
    return similar_items[1:top_n+1]

In [22]:
def recommend_for_user_by_diet(user_id, top_n=5):
    if user_id not in df['user_id'].unique():
        return f"User '{user_id}' not found."
    
    # Get items purchased by the user
    user_items = df[df['user_id'] == user_id]['item'].unique()

    # Initialize recommendations
    tag_recommendations = pd.Series(dtype="float64")

    for item in user_items:
        if item in tag_similarity_df:
            tag_recommendations = tag_recommendations.add(tag_similarity_df[item], fill_value=0)

    # Remove already purchased items
    tag_recommendations = tag_recommendations.drop(labels=user_items, errors='ignore')
    return tag_recommendations.sort_values(ascending=False).head(top_n)

In [23]:
# Group by season and item, and count purchases
seasonal_popularity = df.groupby(['season', 'item']).size().reset_index(name='purchase_count')

# Check top items for each season
seasonal_popularity.sort_values(['season', 'purchase_count'], ascending=[True, False]).head(10)

    season            item  purchase_count
16  Spring            Oats              13
2   Spring        Avocados              12
26  Spring          Turkey              12
11  Spring            Eggs              11
13  Spring    Greek Yogurt              11
19  Spring          Quinoa              11
22  Spring        Soy Milk              11
23  Spring         Spinach              11
24  Spring  Sweet Potatoes              11
1   Spring          Apples               9

In [24]:
def get_trending_items_by_season(season, top_n=5):
    if season not in seasonal_popularity['season'].unique():
        return f"Season '{season}' not found."
    
    trending = seasonal_popularity[seasonal_popularity['season'] == season]
    trending = trending.sort_values(by='purchase_count', ascending=False)
    return trending['item'].head(top_n).tolist()

In [25]:
def recommend_seasonal_items_for_user(user_id, current_season, top_n=5):
    if user_id not in df['user_id'].unique():
        return f"User '{user_id}' not found."

    user_items = df[df['user_id'] == user_id]['item'].unique()
    
    trending_items = seasonal_popularity[seasonal_popularity['season'] == current_season]
    trending_items = trending_items.sort_values(by='purchase_count', ascending=False)

    # Exclude already purchased items
    recommendations = trending_items[~trending_items['item'].isin(user_items)]

    return recommendations['item'].head(top_n).tolist()

In [26]:
def hybrid_recommendation(user_id, current_season, top_n=5, 
                          w_collab=0.4, w_content=0.4, w_season=0.2):
    if user_id not in df['user_id'].unique():
        return f"User '{user_id}' not found."

    # --- 1. Collaborative filtering scores ---
    collab_scores = pd.Series(dtype='float64')
    if user_id in user_item_matrix.index:
        user_data = user_item_matrix.loc[user_id]
        user_items = user_data[user_data > 0].index.tolist()
        for item in user_items:
            collab_scores = collab_scores.add(item_similarity_df[item], fill_value=0)
        collab_scores = collab_scores.drop(labels=user_items, errors='ignore')
    
    # --- 2. Content-based filtering scores ---
    content_scores = pd.Series(dtype='float64')
    user_items = df[df['user_id'] == user_id]['item'].unique()
    for item in user_items:
        if item in tag_similarity_df:
            content_scores = content_scores.add(tag_similarity_df[item], fill_value=0)
    content_scores = content_scores.drop(labels=user_items, errors='ignore')

    # --- 3. Seasonal popularity scores ---
    season_items = seasonal_popularity[seasonal_popularity['season'] == current_season]
    seasonal_scores = pd.Series(season_items['purchase_count'].values,
                                index=season_items['item'])
    seasonal_scores = seasonal_scores.drop(labels=user_items, errors='ignore')

    # --- Normalize all scores ---
    def normalize(s):
        return (s - s.min()) / (s.max() - s.min() + 1e-9)

    collab_scores = normalize(collab_scores)
    content_scores = normalize(content_scores)
    seasonal_scores = normalize(seasonal_scores)

    # --- Combine with weights ---
    combined_scores = (w_collab * collab_scores) \
                    .add(w_content * content_scores, fill_value=0) \
                    .add(w_season * seasonal_scores, fill_value=0)

    return combined_scores.sort_values(ascending=False).head(top_n)

In [27]:
# Example: Top 5 recommendations for user U025 in Summer
hybrid_recommendation(user_id="U025", current_season="Summer", top_n=5)

item
Eggs              0.657747
Zucchini          0.549462
Avocados          0.538750
Lentils           0.529649
Sweet Potatoes    0.510553
dtype: float64

In [28]:
from sklearn.model_selection import train_test_split

# Create train-test split by holding out one item per user
def create_train_test_split(df):
    train_data = []
    test_data = []

    for user_id, group in df.groupby("user_id"):
        if len(group) < 2:
            train_data.append(group)
            continue
        
        test_sample = group.sample(1)
        train_sample = group.drop(test_sample.index)

        train_data.append(train_sample)
        test_data.append(test_sample)

    train_df = pd.concat(train_data)
    test_df = pd.concat(test_data)

    return train_df, test_df

train_df, test_df = create_train_test_split(df)
print("Train:", train_df.shape)
print("Test:", test_df.shape)

Train: (450, 11)
Test: (50, 11)

In [29]:
# Recreate user-item matrix for training
user_item_matrix_train = train_df.pivot_table(index='user_id', columns='item', 
                                              values='purchase_date', aggfunc='count').fillna(0)

In [30]:
def precision_recall_at_k(k=5):
    hits = 0
    total_actual = 0
    total_recommended = 0

    for user_id in test_df['user_id'].unique():
        actual_items = test_df[test_df['user_id'] == user_id]['item'].tolist()

        try:
            recs = hybrid_recommendation(user_id=user_id, current_season='Summer', top_n=k)
        except:
            continue

        recommended_items = recs.index.tolist()
        hit_count = len(set(actual_items) & set(recommended_items))

        hits += hit_count
        total_actual += len(actual_items)
        total_recommended += k

    precision = hits / total_recommended if total_recommended else 0
    recall = hits / total_actual if total_actual else 0
    f1 = 2 * (precision * recall) / (precision + recall + 1e-9)

    return precision, recall, f1

In [31]:
precision, recall, f1 = precision_recall_at_k(k=5)
print(f"Precision@5: {precision:.4f}")
print(f"Recall@5: {recall:.4f}")
print(f"F1@5: {f1:.4f}")

Precision@5: 0.0000
Recall@5: 0.0000
F1@5: 0.0000

In [32]:
import pickle

# Create a single dictionary containing all parts of the model
model_data = {
    "item_similarity_df": item_similarity_df,
    "tag_similarity_df": tag_similarity_df,
    "seasonal_popularity": seasonal_popularity,
    "user_item_matrix": user_item_matrix
}

# Save it all into one pickle file
with open("grocery_recommendation_model.pkl", "wb") as f:
    pickle.dump(model_data, f)

print("✅ All model components saved into one pickle file!")

✅ All model components saved into one pickle file!